#!/bin/sh


yes | hpacucli  controller  slot=0  ld 1 delete
hpacucli controller slot=0  create type=ld drives=1I:1:1-1I:1:4 raid=1+0
mkfs.xfs -f -b size=4096 -L DATA /dev/sda
mount -L DATA /var/lib/mysql
chown mysql.mysql /var/lib/mysql
DEBCONF_NONINTERACTIVE_SEEN=true DEBIAN_FRONTEND=noninteractive sh -x /var/lib/dpkg/info/mariadb-server-5.5.postinst configure



hpacucli ctrl slot=3  create type=ld drives=1I:1:1-1I:1:4,2I:1:5-2I:1:7 raid=6
